[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback - serve index.html for routes that don't exist as files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "no-cache"
    Pragma = "no-cache"